import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Home, BarChart2, Package, UserCircle, HelpCircle, Settings } from "lucide-react"; // Import icons

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <div className="flex h-screen bg-gray-100">
            {/* Sidebar */}
            <aside className="w-64 bg-white shadow-md">
              <div className="p-4">
                <h1 className="text-2xl font-bold text-primary">SupplyChainX</h1>
              </div>
              <nav className="mt-6">
                <Link href="/" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <Home className="mr-3 h-5 w-5" />
                  Home
                </Link>
                <Link href="/dashboard" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <BarChart2 className="mr-3 h-5 w-5" />
                  Dashboard
                </Link>
                <Link href="/register" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <HelpCircle className="mr-3 h-5 w-5" />
                  Add Product
                </Link>
                <Link href="/tracking" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <Package className="mr-3 h-5 w-5" />
                  Tracking
                </Link>
                <Link href="/profile" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <UserCircle className="mr-3 h-5 w-5" />
                  Profile
                </Link>
                <Link href="/help" className="flex items-center px-4 py-2 text-gray-700 hover:bg-gray-200">
                  <HelpCircle className="mr-3 h-5 w-5" />
                  Help Center
                </Link>
              </nav>
            </aside>

            {/* Main content */}
            <main className="flex-1 overflow-y-auto">
              <header className="bg-white shadow-sm">
                <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
                  <Button variant="outline">
                    <Settings className="mr-2 h-4 w-4" /> Settings
                  </Button>
                </div>
              </header>
              <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
